### ISSUE TITLE
Consistently displaying 0it [00:00, ?it/s]

### ISSUE THREAD

**Issue by t7r** [rixx/stepmania-to-sqlite#1]
Did as the readme indicates by doing pip install stepmania-to-sqlite. Tried the arguments as indicated but I keep getting this output:
0it [00:00, ?it/s]

I checked every requirement appeared to be installed along with their corresponding versions.

Attached is a screenshot showing commands I've tried. If the program is working, is there something wrong with any of the arguments?

![stepmania-to-sqlite error](https://user-images.githubusercontent.com/54184504/90322533-86677d00-df23-11ea-8605-7b18a046d78a.jpg)

Not in the image: also tried double-backslashes instead of a single one to no avail.

Thanks!

**Comment by rixx** [comment]
It seems like `stepmania-to-sqlite` never respected the `--location` flag in the first place, and I didn't notice. I fixed it and released v0.2 just now.

**Comment by t7r** [comment]
Just upgraded and unfortunately the same issue still persists. Even tried putting a dummy StepMania directory at the root directory and ran stepmania-to-sqlite without a location flag and still does that. Should be noted it produces a blank songs.db file.

**Comment by rixx** [comment]
The script is looking for a `Songs` directory within the given location. It shouldn't have problems with whitespace in path names, I hope, but I'm not sure and I have no way to test cross-platform availability.

I just released v0.3 that will show explicit errors if no song files can be found.

**Comment by t7r** [comment]
Just upgraded to 0.3. Below is the error that appears when attempting to use the location flag pointing to the corresponding StepMania folder with `Songs` inside it.

```
$ stepmania-to-sqlite songs.db --location "/e/users/t7r/documents/other programs/stepmania"
  0%|          | 0/2360 [00:00<?, ?it/s]Found 2360 songs.
ERROR: argument of type 'WindowsPath' is not iterable
  0%|          | 0/2360 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\t7r\AppData\Local\Programs\Python\Python37-32\Scripts\stepmania-to-sqlite.exe\__main__.py", line 4, in <module>
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\stepmania_to_sqlite\cli.py", line 25, in <module>
    update()
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\stepmania_to_sqlite\cli.py", line 22, in update
    utils.get_songs(db, changed_only=True, save=True, location=location)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\stepmania_to_sqlite\utils.py", line 209, in get_songs
    songs.append(Song(path))
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\stepmania_to_sqlite\utils.py", line 40, in __init__
    self.seconds = self.get_duration()
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\stepmania_to_sqlite\utils.py", line 155, in get_duration
    ["ffprobe", self.song_path], stderr=subprocess.STDOUT
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1100, in _execute_child
    args = list2cmdline(args)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\subprocess.py", line 511, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```



When I do place the (dummy) StepMania in the root drive folder, this shows up after running just `stepmania-to-sqlite songs.db`:

```
$ stepmania-to-sqlite songs.db
Traceback (most recent call last):
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\t7r\AppData\Local\Programs\Python\Python37-32\Scripts\stepmania-to-sqlite.exe\__main__.py", line 4, in <module>
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\stepmania_to_sqlite\cli.py", line 25, in <module>
    update()
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\stepmania_to_sqlite\cli.py", line 22, in update
    utils.get_songs(db, changed_only=True, save=True, location=location)
  File "c:\users\t7r\appdata\local\programs\python\python37-32\lib\site-packages\stepmania_to_sqlite\utils.py", line 198, in get_songs
    raise Exception(f"No song files found!")
Exception: No song files found!
```

**Comment by rixx** [comment]
You don't need to place a dummy folder – all that proves is to show that if the script is pointed to an empty directory, it will not find any songs.

The problem lies with the external script that is called to determine the duration of a song – this is not cross-platform compatible. Currently, even the call to that external script fails, but once I fix that (or once you upgrade to Python 3.8, where this issue does not exist), it will continue to fail because you don't have `ffprobe`.

I have released v0.4 that will not even try to figure out song durations on Windows. In the future, as this is only a side project, I have no intention of maintaining Windows support, though I'll of course merge any Pull Requests.

**Comment by t7r** [comment]
Awesome. v0.4 runs just fine. Don't exactly need song durations for now. Many thanks!
